### ISSUE TITLE
-open not working in 1.6.2

### ISSUE THREAD

**Issue by 7AC** [alloy/terminal-notifier#125]
I'm using the same example as the `README`:

```
terminal-notifier -title '💰' -message 'Check your Apple stock!' -open 'http://finance.yahoo.com/q?s=AAPL'
```

I'm on Mac OS 10.10.1 and running terminal-notifier 1.6.2 installed via homebrew. My default browser is Safari 8.0.2, I tried with `-activate com.apple.Safari` but it doesn't activate no matter what. I'm using Terminal 2.5.

Some of the closed issues suggested to reinstall terminal-notifier, I tried that too but no luck.

**Comment by julienXX** [comment]
Does the notification appear at least?

**Comment by 7AC** [comment]
Yes, but when I click it nothing happens (unlike other notifications not generated by terminal-notifier).

**Comment by julienXX** [comment]
Anything in Console.app that could be related?

**Comment by 7AC** [comment]
I checked yesterday and didn't see anything, I just tried again to check and it worked. The only thing that happened since yesterday is a reboot. Thank you for your help.

**Comment by julienXX** [comment]
No problem, glad it solved itself :)
