### ISSUE TITLE
Multiple notifications at once

### ISSUE THREAD

**Issue by jasonlfunk** [alloy/terminal-notifier#126]
Hello,

Is it possible to display multiple notifications at once? I'm running two separate testing suites that may have different results. The newest notification is always replacing the older one even though they contain different information. Is there anyways to prevent this?

**Comment by Alvaroctal** [comment]
months ago I was looking for the same, as far as I know is not posible with terminal-notifier.

**Comment by reggi** [comment]
+1 :rainbow: :+1:

**Comment by julienXX** [comment]
Still not possible see https://github.com/alloy/terminal-notifier/issues/35.
