### ISSUE TITLE
The command line isn't working on the latest Yosemite 10.10.4 beta

### ISSUE THREAD

**Issue by ValHook** [alloy/terminal-notifier#130]
I have the latest Mac OS X Yosemite 10.10.4 public beta. Just wanted to tell you that the command line doesn't work on this build, it just doesn't do anything. I'm a big fan. Hope you can fix it when you have the time.

Val.

**Comment by julienXX** [comment]
Thanks for bringing this up. Unfortunately I don't have access to the betas ATM but I hope it will be okay when it's released. Can you see something in Console.app?

**Comment by ValHook** [comment]
Well, I rebooted my computer and automagically it worked again. I guess it was a single and random issue.
